[[Xorg_libXdamage]]
arch = "aarch64"
git-tree-sha1 = "3ab0a3584e29ec4ad9c9cc92e465cf775a8ae7b1"
libc = "glibc"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "2c3a639bd6600a7dcde60ccc96f87d569378241de0e7497cc2dbcd2de25583b7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.aarch64-linux-gnu.tar.gz"
[[Xorg_libXdamage]]
arch = "aarch64"
git-tree-sha1 = "fce48b9eda5d1b1a9d7a5c71ec26b09686b5892d"
libc = "musl"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "53c408a11ce5de13b9400d71ff57e30a3fe708bd275e389c67999fd47076931f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.aarch64-linux-musl.tar.gz"
[[Xorg_libXdamage]]
arch = "aarch64"
git-tree-sha1 = "24adc070021904eb77cc22a6e23eca1e5cc38cee"
os = "freebsd"

    [[Xorg_libXdamage.download]]
    sha256 = "541338296587fbedabdaf5346ff3983b81f9066a4b46bad9d7b11c39864512bc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXdamage]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4bf10a6495f31e183f5e8eedc44f383349f48969"
libc = "glibc"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "1540cae4962718934031aabd3784a3f494ed0e2fe6348ba63fe8174b83405613"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXdamage]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb39ccead7018460d512528219efce772ac8c27b"
libc = "musl"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "635783af92718f78b3b54863e2d3a93cf4c3e5112669621885d5f1670c0fb220"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXdamage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af754fcab26857b5dcbcf5601ea562707b0218a4"
libc = "glibc"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "847b45c197e01af0c8618721499ad579deced9b9906198dc06295919675f7e43"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXdamage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ed9c498a9ac70c514c1a615c5f51ab098d9e6ff"
libc = "musl"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "2fc1e1cc003e262db78fb8a2aa3938c4e5ec382930f614eb3e0d9f57034a3ec5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXdamage]]
arch = "i686"
git-tree-sha1 = "9352a10e1c10c791798c76cd78a6753966d02fbf"
libc = "glibc"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "bee65aeb03e480ae3f37d20138aca02fdf2b7f09497918f95595904138263e53"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.i686-linux-gnu.tar.gz"
[[Xorg_libXdamage]]
arch = "i686"
git-tree-sha1 = "dbfc272c801c72fd4f8acba201e51d7aadef609e"
libc = "musl"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "465a8649a15801cb81bd97b431d0c9b2b637f34a8cf439644a4edb76cffed791"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.i686-linux-musl.tar.gz"
[[Xorg_libXdamage]]
arch = "powerpc64le"
git-tree-sha1 = "ccd98df6c633700d2f527743cfdd8c048a5321fe"
libc = "glibc"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "e43a76f3e6a696d52559b87542a8cc058e20db719e45fd05eeb60ac73556b640"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXdamage]]
arch = "riscv64"
git-tree-sha1 = "5efdaedcbd5ff22fa2e3500355d4df4290b5bb47"
libc = "glibc"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "7b61189567e00be6789c8e3cdd5f791cabb63ffc410c0992d974133ce234014f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.riscv64-linux-gnu.tar.gz"
[[Xorg_libXdamage]]
arch = "x86_64"
git-tree-sha1 = "43af9d2af5468692a2d341b8ab0e19e0477b1458"
libc = "glibc"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "d5eae0f4b9029da35c9470d17c87f1d5c9325e3488f6b76bd1ce2e0f0b24faba"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.x86_64-linux-gnu.tar.gz"
[[Xorg_libXdamage]]
arch = "x86_64"
git-tree-sha1 = "3c6968f20ba1208843bfa48e02df208c10824bcf"
libc = "musl"
os = "linux"

    [[Xorg_libXdamage.download]]
    sha256 = "f346ba5b55008a2247f24d1958ced0f2fd56a18c10693b5f983b6ed16a70eb5a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.x86_64-linux-musl.tar.gz"
[[Xorg_libXdamage]]
arch = "x86_64"
git-tree-sha1 = "7ec1d2e9edc60131a571c5e86573d386f7586e60"
os = "freebsd"

    [[Xorg_libXdamage.download]]
    sha256 = "da6256b2f0160eae95073571d9dc5dc00d3107be3fec9de6f7416d2d275b663f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdamage_jll.jl/releases/download/Xorg_libXdamage-v1.1.7+0/Xorg_libXdamage.v1.1.7.x86_64-unknown-freebsd.tar.gz"
